blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/nextwit/dev-template-repository/discussions
    about: For general questions and community discussion, please use GitHub Discussions.
